Ajustes em testes de integração

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -6,7 +6,6 @@ on:
     branches: [ "master" ]
 
 jobs:
-
   build:
 
     strategy:
@@ -35,6 +34,40 @@ jobs:
     - name: Setup MSBuild.exe
       uses: microsoft/setup-msbuild@v2
 
+    # Set up Docker Compose
+    - name: Set up Docker Compose
+      run: |
+        echo "version: '3.8'
+
+        services:
+          db:
+            image: postgres:latest
+            environment:
+              POSTGRES_USER: testuser
+              POSTGRES_PASSWORD: 102030
+              POSTGRES_DB: testdb
+            ports:
+              - '5432:5432'" > docker-compose.yml
+
+    # Start the database
+    - name: Start database
+      run: docker-compose up -d
+
+    # Wait for the database to be ready
+    - name: Wait for Postgres
+      run: |
+        echo "Waiting for Postgres to be ready..."
+        for i in {1..30}; do
+          if docker exec $(docker-compose ps -q db) pg_isready -U testuser -d testdb; then
+            echo "Postgres is ready!"
+            exit 0
+          fi
+          echo "Waiting..."
+          sleep 2
+        done
+        echo "Postgres did not become ready in time!"
+        exit 1
+
     # Execute all unit tests in the solution
     - name: Execute unit tests
       run: dotnet test $env:Test_Project_Path
@@ -44,3 +77,8 @@ jobs:
       run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
       env:
         Configuration: ${{ matrix.configuration }}
+
+    # Clean up Docker containers
+    - name: Clean up
+      if: always()
+      run: docker-compose down
